"""Stable Python SAST vulnerability and misuse rule metadata."""

from security_auditor.core.models import Confidence, Severity
from security_auditor.scanners._common import StaticRule


RULES = (
    StaticRule("SAST.PYTHON.COMMAND_INJECTION", "Potential command injection",
               "Untrusted input reaches a shell command sink through local data flow.",
               "vulnerability", Severity.HIGH, Confidence.HIGH,
               "A local source-to-sink path reaches shell command execution.",
               "Use an argv list with shell disabled; validate arguments and executable selection.",
               "CWE-78", ("python", "command")),
    StaticRule("SAST.PYTHON.SQL_INJECTION", "Potential SQL injection",
               "Untrusted input reaches an interpolated SQL query.",
               "vulnerability", Severity.HIGH, Confidence.HIGH,
               "A local source-to-sink path constructs SQL text with external data.",
               "Use parameterized queries supported by the database driver.",
               "CWE-89", ("python", "sql")),
    StaticRule("SAST.PYTHON.PATH_TRAVERSAL", "Potential arbitrary file access",
               "External path data reaches a file operation without a recognized boundary guard.",
               "vulnerability", Severity.MEDIUM, Confidence.MEDIUM,
               "A local source-to-sink path reaches filesystem access.",
               "Resolve against an allowed base and verify the resolved path remains inside it.",
               "CWE-22", ("python", "filesystem")),
    StaticRule("SAST.PYTHON.UNSAFE_DESERIALIZATION", "Unsafe deserialization of external data",
               "External data reaches a Python deserialization API.",
               "vulnerability", Severity.HIGH, Confidence.HIGH,
               "A local source-to-sink path reaches an unsafe deserializer.",
               "Use a data-only format and validate its schema; do not deserialize untrusted Python objects.",
               "CWE-502", ("python", "deserialization")),
    StaticRule("SAST.PYTHON.DYNAMIC_CODE_EXEC", "Potential dynamic code injection",
               "External data reaches dynamic Python code evaluation.",
               "vulnerability", Severity.HIGH, Confidence.HIGH,
               "A local source-to-sink path reaches dynamic code execution.",
               "Remove dynamic execution of external input; use a data parser or explicit dispatch table.",
               "CWE-94", ("python", "dynamic_code")),
    StaticRule("SAST.PYTHON.TLS_VERIFY_DISABLED", "TLS certificate verification disabled",
               "A network request explicitly disables certificate verification.",
               "vulnerability", Severity.MEDIUM, Confidence.HIGH,
               "The call passes verify=False to a supported HTTP client.",
               "Enable certificate verification and configure trusted CA material as needed.",
               "CWE-295", ("python", "tls")),
    StaticRule("SAST.PYTHON.UNSAFE_YAML_LOAD", "Potential unsafe YAML loading",
               "yaml.load is used without a recognized safe loader; impact depends on library version and configuration.",
               "vulnerability", Severity.MEDIUM, Confidence.MEDIUM,
               "The call lacks an explicit safe loader signal.",
               "Use yaml.safe_load or explicitly specify SafeLoader for data-only input.",
               "CWE-502", ("python", "yaml")),
    StaticRule("SAST.PYTHON.INSECURE_TEMP_FILE", "Predictable temporary file API",
               "tempfile.mktemp creates a name without opening it, allowing a race before use.",
               "vulnerability", Severity.MEDIUM, Confidence.HIGH,
               "The call invokes tempfile.mktemp.",
               "Use NamedTemporaryFile or mkstemp with safe permissions and explicit cleanup.",
               "CWE-377", ("python", "temporary_file")),
)
RULE_BY_ID = {rule.id: rule for rule in RULES}
